version: "3"

dotenv:
  - .env

tasks:
  lmcache:
    cmds:
      - uv run lmcache_server 127.0.0.1 65432

  vllm:
    env:
      LMCACHE_CONFIG_FILE: lmcache.yml
    cmds:
      - >
        uv run vllm serve "Qwen/Qwen3-0.6B"
        --max-model-len 32768
        --kv-transfer-config '{"kv_connector": "LMCacheConnectorV1", "kv_role": "kv_both"}'

  print-env:
    cmds:
      - uv run python -c "import torch; print(torch.__version__); print(torch.cuda.get_arch_list()); print(torch.randn(1).cuda())"
